
services:
  digilite_postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: support_tickets
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - digilite_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ticket-network

networks:
  ticket-network:
    driver: bridge

volumes:
  digilite_postgres_data: 