version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=support_tickets
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - database
    command: ["sh", "-c", "npm run migrate:up && npm run dev"]
    networks:
      - ticket-network-all

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - ticket-network-all

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: support_tickets
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ticket-network-all

volumes:
  postgres_data:
  
networks:
  ticket-network-all:
    driver: bridge